### ISSUE TITLE
CTRL+F search highlight color is not inline with theme

### ISSUE THREAD

**Issue by jonassvedas** [dragonejt/nord-firefox#1]
The default Firefox search highlight color is not matching the nord color scheme, seems like it can be modified by updating the textSelectBackgroundAttention field. See: https://support.mozilla.org/en-US/questions/916946.

**Comment by dragonejt** [comment]
I just checked the Firefox theme docs and it seems that the official method of changing the highlight color of the Ctrl+F bottom bar field is the "toolbar_field_highlight" field in manifest.json, and that is in fact set to #5e81ac, which is a color in the Nord Theme. However, perhaps due to the new Proton design, the highlight color of the Ctrl+F field is not #5e81ac even though it is set to that color.

The ui.textSelectBackgroundAttention field is a field in the Firefox about:config page, and I am pretty sure it is incompatible with the manifest.json theme type, unless evidence determines otherwise. Therefore I cannot use that field to change the Ctrl+F highlight color.

I will leave this issue open for any comments, and close if after a week if there are no other comments.

See the following image from https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme for reference about the method of changing the Ctrl+F bottom bar field highlight color.

![image](https://user-images.githubusercontent.com/23247706/123461795-5dc9fe00-d59e-11eb-8eb5-939f88c2f59e.png)
